INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Nutela Pote Grande', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Chocolate', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Leite Condensado', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Doce de Leite', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Leite Ninho', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Roll Maltine', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Bolacha Oreo', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Nesquick', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Chocolate Bis', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Chocolate Sonho de Valsa', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Fini', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Granulado Colorido', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Tubete', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Castanha Moída', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Casquinha Cone', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Casquinha Cesta', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Casquinha Taco', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Copo Ice Cream Roll', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Copo Gelato', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Copo Milk Shake', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Morango', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Framboesa', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Mirtilo', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Banana', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Limão', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Leite', 5, 50, NULL);
INSERT INTO `produto` (`cod_barra`, `nome_produto`, `estoque_min`, `estoque_ideal`, `qtd_estoque`) VALUES ('', 'Chantily', 5, 50, NULL);